# paths
deploy_root: "/opt/{{app_name}}"
celery_bin: "{{deploy_root}}/.env/bin/celery"
unix_socket_name: "/tmp/{{app_name}}-wsgi.sock"
# nginx
http_port: 80
# misc
webapp_archive_location: /tmp/src.tar
