# accounts
user_name: "{{app_name}}"
group_name: "{{app_name}}"
# paths
deploy_root: "/opt/{{app_name}}"
src_root: "{{deploy_root}}/src"
celery_bin: "{{src_root}}/.env/bin/celery"
# nginx
http_port: 80
# misc
webapp_archive_location: /tmp/src.tar.gz
# required packages
required_apt_packages:
    - build-essential
    - rsync
    - python3
    - python3-pip
    - python3-dev
    - software-properties-common
    - libpq-dev
    - nginx
    - curl
    - redis-server
    - gcc
    - sudo
required_yum_packages:
    - rsync
    - python34u
    - python34u-devel
    - python34u-pip
    - nginx
    - curl
    - redis
    - gcc
required_pacman_packages:
    - rsync
    - python-pip
    - nginx
    - curl
    - redis
    - gcc
    - sudo
