# accounts
user_name: "{{app_name}}"
group_name: "{{app_name}}"
# paths
deploy_root: "/opt/{{app_name}}"
src_root: "{{deploy_root}}/src"
# nginx
http_port: 80
# misc
webapp_archive_location: /tmp/src.tar.gz
# required packages
required_apt_packages:
    - build-essential
    - rsync
    - python-virtualenv
    - python-dev
    - software-properties-common
    - nginx
    - curl
required_yum_packages:
    - rsync
    - python-virtualenv
    - python-devel
    - nginx
    - curl
required_pacman_packages:
    - rsync
    - python-virtualenv
    - nginx
    - curl
