- name: ensure directories
  action: file state=directory path={{item}} owner={{user_name}} group={{group_name}}
  with_items:
    - "{{deploy_root}}"
- include: redis.yml
- include: nginx.yml
- include: configuration.yml
- name: copy source
  copy: src=../src_pkg.tar dest={{webapp_archive_location}}
  register: sources
  notify: reload nginx config
- include: install_sources.yml
  when: sources.changed or configuration.changed
- name: configure supervisor
  action: template src=../templates/supervisor.j2 dest=/etc/supervisor/conf.d/{{app_name}}-wsgi.conf
  register: supervisor_conf
- shell: supervisorctl reload
  when: supervisor_conf.changed and in_docker is not defined
