- name: ensure directories
  action: file state=directory path={{item}} owner={{user_name}} group={{group_name}}
  with_items:
    - {{deploy_root}}
    - {{deploy_root}}/conf.d
- include: nginx.yml
- include: virtualenv.yml
- include: configuration.yml
- name: ensure uwsgi is installed
  shell: {{deploy_root}}/virtualenv/bin/easy_install -U uwsgi creates={{deploy_root}}/virtualenv/bin/uwsgi
- name: copy source
  copy: src=../src_pkg.tar dest={{webapp_archive_location}}
  register: sources
- include: install_sources.yml
  when: sources.changed or configuration.changed
- name: configure supervisor
  action: template src=../templates/supervisor.j2 dest=/etc/supervisor/conf.d/{{app_name}}-wsgi.conf
  register: supervisor_conf
- shell: supervisorctl reload
  when: supervisor_conf.changed
