# accounts
user_name: "{{app_name}}"
group_name: "{{app_name}}"
required_packages:
    - software-properties-common
    - python-software-properties
    - curl
    - wget
    - ca-certificates
    - libxml2-dev
    - libxslt1-dev
    - git
    - supervisor
    - python-setuptools
    - python-virtualenv
    - python-pycurl
    - python-dev
    - libevent-dev
    - libpq-dev
